apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pkvsbvn98-go 
  janus-idp.io/tekton: pkvsbvn98-go
  backstage.io/kubernetes-id: pkvsbvn98-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pkvsbvn98-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml