apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: pkvsbvn98-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pkvsbvn98-go 
  name: pkvsbvn98-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: pkvsbvn98-go 
